
package com.evaluacion.servidor.com.claro;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidarNitService", targetNamespace = "http://claro.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidarNitService {


    /**
     * 
     * @return
     *     returns java.util.List<com.claro.ResponseModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarNitValidos", targetNamespace = "http://claro.com/", className = "com.claro.ListarNitValidos")
    @ResponseWrapper(localName = "listarNitValidosResponse", targetNamespace = "http://claro.com/", className = "com.claro.ListarNitValidosResponse")
    @Action(input = "http://claro.com/ValidarNitService/listarNitValidosRequest", output = "http://claro.com/ValidarNitService/listarNitValidosResponse")
    public List<ResponseModel> listarNitValidos();

    /**
     * 
     * @param nit
     * @return
     *     returns com.claro.ResponseModel
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validarNit", targetNamespace = "http://claro.com/", className = "com.claro.ValidarNit")
    @ResponseWrapper(localName = "validarNitResponse", targetNamespace = "http://claro.com/", className = "com.claro.ValidarNitResponse")
    @Action(input = "http://claro.com/ValidarNitService/validarNitRequest", output = "http://claro.com/ValidarNitService/validarNitResponse")
    public ResponseModel validarNit(
        @WebParam(name = "nit", targetNamespace = "")
        String nit);

}
