
package com.claro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidarNitService", targetNamespace = "http://claro.com/", wsdlLocation = "http://c24d-143-208-56-89.ngrok.io/ValidarNitService/ValidarNitService?WSDL")
public class ValidarNitService_Service
    extends Service
{

    private final static URL VALIDARNITSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDARNITSERVICE_EXCEPTION;
    private final static QName VALIDARNITSERVICE_QNAME = new QName("http://claro.com/", "ValidarNitService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://c24d-143-208-56-89.ngrok.io/ValidarNitService/ValidarNitService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDARNITSERVICE_WSDL_LOCATION = url;
        VALIDARNITSERVICE_EXCEPTION = e;
    }

    public ValidarNitService_Service() {
        super(__getWsdlLocation(), VALIDARNITSERVICE_QNAME);
    }

    public ValidarNitService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDARNITSERVICE_QNAME, features);
    }

    public ValidarNitService_Service(URL wsdlLocation) {
        super(wsdlLocation, VALIDARNITSERVICE_QNAME);
    }

    public ValidarNitService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDARNITSERVICE_QNAME, features);
    }

    public ValidarNitService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidarNitService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidarNitService
     */
    @WebEndpoint(name = "ValidarNitServicePort")
    public ValidarNitService getValidarNitServicePort() {
        return super.getPort(new QName("http://claro.com/", "ValidarNitServicePort"), ValidarNitService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidarNitService
     */
    @WebEndpoint(name = "ValidarNitServicePort")
    public ValidarNitService getValidarNitServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://claro.com/", "ValidarNitServicePort"), ValidarNitService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDARNITSERVICE_EXCEPTION!= null) {
            throw VALIDARNITSERVICE_EXCEPTION;
        }
        return VALIDARNITSERVICE_WSDL_LOCATION;
    }

}
